openapi: 3.0.3
info:
  title: Main Service API
  version: 1.0.0
servers:
- url: /
paths:
  /users:
    post:
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users_body'
        required: true
      responses:
        "201":
          description: User created
        "400":
          description: Wrong format
        "401":
          description: Session ID is missing or invalid
        "5XX":
          description: Unexpected error
  /users/me:
    patch:
      summary: Update user's own data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users_me_body'
        required: true
      responses:
        "200":
          description: User updated
        "400":
          description: Wrong format
        "401":
          description: Session ID is missing or invalid
        "5XX":
          description: Unexpected error
      security:
      - cookieAuth: []
  /auth:
    post:
      summary: Authenticate a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_body'
        required: true
      responses:
        "200":
          description: |
            Successfully authenticated. The session ID is returned in a cookie named `SESSIONID`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              style: simple
              explode: false
              schema:
                type: string
                example: SESSIONID=abcde12345
        "400":
          description: Wrong format
        "401":
          description: Wrong credentials
        "5XX":
          description: Unexpected error
      security:
      - cookieAuth: []
components:
  schemas:
    auth_body:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
    users_me_body:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        email:
          type: string
          format: email
        phoneNumber:
          type: string
    users_body:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: SESSIONID
      in: cookie
