version: '3.8'
services:
  main_service:
    build: ./main_service
    ports:
      - "8765:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: