services:
  main_service:
    build:
      context: ./
      dockerfile: ./main_service/Dockerfile
    ports:
      - "8764:8080"
    depends_on:
      main_db:
        condition: service_started
      posts_service:
        condition: service_started
      statistics_service:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      MAIN_DB_HOST: main_db
      MAIN_DB_USERNAME: test
      MAIN_DB_PASSWORD: test
      MAIN_DB_NAME: test
      POSTS_GRPC_SERVER: posts_service:50051
      STATISTICS_GRPC_SERVER: statistics_service:50051
      KAFKA_SERVER: kafka:9092

  main_db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  posts_service:
    build: ./posts_service
    depends_on:
      - posts_db
    environment:
      POSTS_DB_HOST: posts_db
      POSTS_DB_USERNAME: test
      POSTS_DB_PASSWORD: test
      POSTS_DB_NAME: test

  posts_db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  statistics_service:
    build: ./statistics_service
    depends_on:
      statistics_db:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      STATS_DB_HOST: statistics_db:9000
      STATS_DB_USERNAME: test
      STATS_DB_PASSWORD: test
      KAFKA_SERVER: kafka:9092

  statistics_db:
    image: yandex/clickhouse-server:latest
    environment:
      - CLICKHOUSE_USER=test
      - CLICKHOUSE_PASSWORD=test

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
