/*
 * Main Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	sw "main_service/go"
)

func main() {
	log.Printf("Server started")

	sw.Init()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
