/*
 * Main Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UsersMeBody struct {
	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	BirthDate string `json:"birthDate,omitempty"`

	Email string `json:"email,omitempty"`

	PhoneNumber string `json:"phoneNumber,omitempty"`
}
