/*
 * Main Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TopUser struct {
	Name string `json:"name,omitempty"`

	LikesCount int64 `json:"likesCount"`
}
