/*
 * Main Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PostStats struct {
	Id int64 `json:"id,omitempty"`

	ViewCount int64 `json:"viewCount"`

	LikeCount int64 `json:"likeCount"`
}
