/*
 * Main Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TopPost struct {
	Id string `json:"id,omitempty"`

	AuthorName string `json:"authorName,omitempty"`

	Count int32 `json:"count"`
}
