/*
 * Main Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AuthPost",
		strings.ToUpper("Post"),
		"/auth",
		AuthPost,
	},

	Route{
		"UsersMePatch",
		strings.ToUpper("Patch"),
		"/users/me",
		UsersMePatch,
	},

	Route{
		"UsersPost",
		strings.ToUpper("Post"),
		"/users",
		UsersPost,
	},

	Route{
		"PostsGet",
		strings.ToUpper("Get"),
		"/posts",
		PostsGet,
	},

	Route{
		"PostsPost",
		strings.ToUpper("Post"),
		"/posts",
		PostsPost,
	},

	Route{
		"PostsPostIdDelete",
		strings.ToUpper("Delete"),
		"/posts/{postId}",
		PostsPostIdDelete,
	},

	Route{
		"PostsPostIdGet",
		strings.ToUpper("Get"),
		"/posts/{postId}",
		PostsPostIdGet,
	},

	Route{
		"PostsPostIdPatch",
		strings.ToUpper("Patch"),
		"/posts/{postId}",
		PostsPostIdPatch,
	},
}
