@startuml Context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "Social network user")
System(service, "Social network service", "Multiple microservices in Docker")
Rel(user, service, "Creates, modifies and deletes posts, comments, leaves likes, watches statistics etc")

@enduml